webtalk_init -webtalk_dir E:\\vzhao\\vzhao\\zynq\\2014_2_zynq_labs\\lab3\\lab3.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期日 三月 6 22:32:58 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "93n27983bm0pdmijinmtpgt2lc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1457271600301" -context "sdk\\\\hardware/1457271600301"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1457271600301"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1457271600301"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.2" -context "sdk\\\\hardware/1457271600301"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1457271600301"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1457271600301"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1457271600301"
webtalk_add_data -client sdk -key uid -value "1457271692076" -context "sdk\\\\bsp/1457271692076"
webtalk_add_data -client sdk -key hwid -value "1457271600301" -context "sdk\\\\bsp/1457271692076"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1457271692076"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1457271692076"
webtalk_add_data -client sdk -key uid -value "1457271761605" -context "sdk\\\\application/1457271761605"
webtalk_add_data -client sdk -key hwid -value "1457271600301" -context "sdk\\\\application/1457271761605"
webtalk_add_data -client sdk -key bspid -value "1457271692076" -context "sdk\\\\application/1457271761605"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1457271761605"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1457271761605"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1457271761605"
webtalk_transmit -clientid 4254519965 -regid "" -xml E:\\vzhao\\vzhao\\zynq\\2014_2_zynq_labs\\lab3\\lab3.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\vzhao\\vzhao\\zynq\\2014_2_zynq_labs\\lab3\\lab3.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\vzhao\\vzhao\\zynq\\2014_2_zynq_labs\\lab3\\lab3.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
